#内置tomcat端口及应用上下文配置
server:
  port: 8888
  servlet:
    context-path: /sbox
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
    min-spare-threads: 100

spring:
  application:
    name:        sdk-client
#设置文件上传大小限制
  servlet:
     multipart:
        enabled: true   # 启用http上传处理
        max-file-size: 10MB # 设置单个文件的最大长度
        max-request-size: 10MB # 设置最大的请求文件的大小
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    #授权CREATE USER 'root'@'%' IDENTIFIED BY 'root'; grant all privileges on *.* to 'root'@'%' ;
    url: jdbc:mysql://127.0.0.1:3306/dbox?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    uname: root
    password: 123456
    #下面为连接池的补充设置，应用到上面所有数据源中
    #初始化大小，最小，最大
    initialSize: 5
    minIdle: 2
    maxActive: 50
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,log4j
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

# 独立数据库的mybatis设置
self:
  #以SelfMapping结尾的xml文件
  mapperLocation: classpath*:com/core/**/*SelfMapping.xml
  #SelfMapper目录下的java文件
  basePackage: com.core.**.selfMapper

# log4j2 配置文件路径
logging:
  config: classpath:log4j2.xml

#无需拦截的相关请求资源
interceptor-config:
  login-interceptor-exclude-path:
  - /user/login
  - /user/check
  - /public/upload/getFile

#会话保持时间(单位小时)
sessionTime: 10

# 该注解使用于通过启业云平台上传和下载文件
web_protocol: http://
root_domain: proj.lets.aysaas.com
www_domain: www.proj.lets.aysaas.com:23121
static_domain: staticsafety.proj.lets.aysaas.com:23121
fileIO_domain: fileio.proj.lets.aysaas.com:23121
application_name: AYSaaS-zhonghua
#前端定制API、PAGE访问域名
node_www_domain: www.proj.lets.aysaas.com:23121
sdk_securityDes3IV: 01234567
sdk_securityDes3Key: 0123456789abcd0123456789

#smsConfig
send_flag: true
send_server: http://www.sendcloud.net
send_api: http://api.sendcloud.net/apiv2/mail/send
send_template_api: http://api.sendcloud.net/apiv2/mail/sendtemplate
send_sms_api: http://www.sendcloud.net/smsapi/send
send_voice_api: http://www.sendcloud.net/smsapi/sendVoice
sms_user: xingzhongYJJY
sms_key: gTQKTAHPrJ1z10AdUEFL38MOeJTWg5BF
MAX_RECEIVERS: 100
MAX_MAILLIST: 5

# 该注解用于设置Cookie的domain域
domain: 127.0.0.1

# 该注解使用于文书生成
docWriter:
  # 文书生成临时目录
  tempPath: E:\\docWriter\\tempPath\\

# 该注解使用于分布式定时任务
elastic:
  job:
    zk:
      serverLists: 127.0.0.1:2181
      namespace: elastic_job

